[package]
name = "doctool_desktop"
version = "1.0.0"
description = "万能格式转换器 离线版"
authors = ["MR.谢 <370298218@qq.com>"]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = [ "dialog-confirm", "fs-read-dir", "fs-create-dir", "fs-write-file", "fs-exists", "dialog-ask", "fs-read-file", "dialog-save", "dialog-message", "dialog-open", "path-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
base64 = "0.22"
ed25519-dalek = "2"
hmac = "0.12"
winreg = "0.52"

[features]
custom-protocol = ["tauri/custom-protocol"]
